version: 2.1

orbs:
  codacy: codacy/base@12.2.0

workflows:
  version: 2
  compile_test_deploy:
    jobs:
      - codacy/checkout_and_version:
          write_sbt_version: true
      - codacy/sbt:
          name: check_format_populate_cache_and_compile
          context: CodacyAWS
          persist_to_workspace: true
          cmd: |
            sbt scalafmtSbtCheck scalafmtCheckAll crossTestCompile
          requires:
            - codacy/checkout_and_version
      - codacy/sbt:
          name: test
          context: CodacyAWS
          cmd: sbt crossTest
          requires:
            - check_format_populate_cache_and_compile
      - codacy/sbt:
          name: publish
          context: CodacyAWS
          no_output_timeout: "30m"
          cmd: sbt retrieveGPGKeys crossPublishSigned sonatypeCentralRelease
          requires:
            - test
          filters:
            branches:
              only:
                - master
